### ISSUE TITLE
[View] Home view

### ISSUE THREAD

**Issue by dahae0320** [GNU-CORNER/BookkyProject_iOS#1]
### 요약
홈화면 프로토타입 제작

### 자세한 설명
백엔드와 api 연동을 위하여 홈화면의 프로토타입을 먼저 제작한다. 기획한 디자인처럼 완전히 구현하지 않고 데이터가 들어갈 요소들을 배치한다. 
## ToDo
- [x] HomeViewTableView
- [x] HomeViewWelcomeView(Text&NoticeButton)
- [x] HomeViewTableViewInCollectionView
- [x] HomeViewBookName/BookImage
- [x] HomeViewRecommandView
- [x] HomeViewCommunityView

**Comment by dongjin97** [comment]
완료
